import Foundation

extension Bundle {
    /// Where the package's own resources — the SVG art — actually are.
    ///
    /// Not `Bundle.module`, and the reason is a packaging trap worth stating. `Bundle.module` is
    /// generated by SwiftPM and looks in exactly one runtime location:
    /// `Bundle.main.bundleURL/ParaBear_ParaBear.bundle`. For a command-line build that is the
    /// directory beside the executable and it works. For an `.app` it is the **bundle root** — and
    /// a loose bundle sitting in an app's root is what `codesign` calls "unsealed contents present
    /// in the bundle root": the signature stops verifying, which for an app distributed to anyone
    /// else is fatal. Its only other candidate is an absolute path into the `.build` directory of
    /// whichever machine compiled it, so a packaged app that relied on it would run on that machine
    /// and trap with "could not load resource bundle" everywhere else.
    ///
    /// So `Scripts/package_app.sh` installs the resource bundle where a bundle belongs,
    /// `Contents/Resources`, and this looks there first. `.module` remains the fallback, which is
    /// what keeps `swift run` and `swift test` working — neither has a `Contents/Resources`.
    static let packagedResources: Bundle = {
        if let resources = Bundle.main.resourceURL,
           let installed = Bundle(url: resources.appendingPathComponent(resourceBundleName)) {
            return installed
        }

        return .module
    }()

    /// Named by SwiftPM as `<package>_<target>.bundle`. `Scripts/package_app.sh` copies the bundle
    /// under this name, so the two have to agree.
    static let resourceBundleName = "ParaBear_ParaBear.bundle"
}
